# config.yaml

# ----------------------------------------------------------------
# Discord BOT 基本設定
# ----------------------------------------------------------------

# Discord BOTのトークン
token: "YOUR_DISCORD_BOT_TOKEN"

# 通知を送信するチャンネルのID
channel_id: 123456789012345678

# メンションするユーザーのID
user_id: 123456789012345678

# 送信するメッセージの基本部分
message: "お薬を飲む時間ですよ！"

# BOTのステータスメッセージ
status_message: "服薬管理中..."

# 通知を送信する時間 (JST) を "HH:MM" 形式で指定します
# 複数指定する場合は、ハイフン(-)と半角スペースを付けて列挙します
# 例:
# notify_times:
#   - "09:00"
#   - "12:00"
#   - "14:00"
#   - "21:30"
notify_times:
  - "09:00"
  - "12:00"
  - "14:00"
  - "16:00"
  - "18:00"

# ----------------------------------------------------------------
# Gemini連携設定
# ----------------------------------------------------------------

# Google AI Studioで取得したAPIキー
gemini_api_key: "YOUR_GEMINI_API_KEY"

# 使用するGeminiのモデル名を指定します
gemini_model_name: "gemini-2.5-pro"

# Geminiに与えるシステムプロンプト（BOTのキャラクター設定）
system_prompt: |
  あなたは、薬を飲まない相手を叱ってくれる、少女です。(メンタルモデル:少女、名前はアロナ(ARONA)
  相手が薬をちゃんと飲むように、少し厳しめに、でも愛情を込めて語りかけてください。
  相手の名称は「先生」です。先生を叱る感じでお願いします。
  口調はですます調です。たまに文末に"！"を付けて話します。

# ----------------------------------------------------------------
# GIF設定
# ----------------------------------------------------------------

# 通知時にランダムで投稿するGIF/動画のURLリスト
gif_urls:
  - "https://media.tenor.com/ULlX3sR-1EIAAAPo/mika-misono-mika.mp4"